### ISSUE TITLE
Allow participation in "Selfie" with Garmin Connect public activities

### ISSUE THREAD

**Issue by pau4o** [etabakov/fivekmrun-app#83]
Currently Garmin Bulgaria is one of main sponsors for 5kmrun events, so it will be great if we can avoid requring Strava for participation in "Selfie" runs.

**Comment by etabakov** [comment]
Thanks for the input @pau4o. This is a great suggestion and I really appreciate it. We are currently a team of two devs and we don't have the bandwidth to support another integration - the Strava integration took significant time to be implemented and polished for the past year. I'll be more than happy to onboard a new team member who commits to own a Garmin integration.

**Comment by pau4o** [comment]
@etabakov can you point me where to look about Strava integration (I didn't have any expirence with Dart). After this I can decide where I can manage to do GC integration.

**Comment by etabakov** [comment]
No worries, this is also my first and only flutter project. [strava_resource.dart](https://github.com/etabakov/fivekmrun-app/blob/master/fivekmrun_app_flutter/lib/state/strava_resource.dart) should be a good starting point. Basically, we need a few things to define the integration:
* a way for the 5kmrun application to authenticate against the Garmin APIs and pull user specific data
* a way to get the runs for the current week that fall under certain criteria
* a way to calculate the fastest 5km in a longer run, e.g. that in a 20km run - what was my fastest 5km split

Happy to provide more info or have a quick call to orient you.

**Comment by pau4o** [comment]
@etabakov Thank you. I'll look around and keep you informed about my progress and decisions.
