### ISSUE TITLE
Add badges for 5kmMAX and SelfieMAX

### ISSUE THREAD

**Issue by etabakov** [etabakov/fivekmrun-app#97]
There are virtual badges that runners receive if they have runs during every single week in the year.

* 5kmMAX is for runners that participated in a official run every week of the year
* SelfieMAX is for runners that participated in with a selfie every week of the year

The badges are attached
![Max](https://github.com/etabakov/fivekmrun-app/assets/2611328/731a61d8-934c-4c81-bd7f-8089fcfe6357)
![MaxSelfie](https://github.com/etabakov/fivekmrun-app/assets/2611328/1c174e73-02c9-414d-a626-9d2728264b8a)

**Comment by mystoev** [comment]
Where are these suppose to go? Should we place them right next to the user's profile photo (similar to Discord's status badge)?

**Comment by etabakov** [comment]
Yes, that's one option - it will be visible only to the current user so main purpose would be self-pride.
Another option is in the result list to show a badge for all users that maxed their runs but at this point this will be a nightmare to calculate. So, profile photo sounds good for a start.

**Comment by mystoev** [comment]
Ok, sounds good. But what would happen, if a person has both? :) Maybe we could give one of those a priority? In the future, we could have a separate "badges" section, with all of them, especially if we add more. For example, a badge for completing all locations, or even add challenges...

**Comment by etabakov** [comment]
Yes, a badge for all locations is on the horizon :D I see two options:
- show one of them on the profile pic with the badge for official runs having priority as it's harder to be achieved
- creating a new tile in the dashboard that is badge box - this will be more scalable. For example, we can show that a runner won a max badge three times in different years similar to how Garmin does it, it will also give us some room to explain what are those badges as it's not obvious what MAX means

![IMG_F0DF56EEE13B-1](https://github.com/etabakov/fivekmrun-app/assets/2611328/8bf986e9-8ca1-4fb8-8287-afb479a85b2d)
